apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-1
  labels:
    account: service-1

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1
  labels:
    app: service-1
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-1
      version: v1
  template:
    metadata:
      labels:
        app: service-1
        version: v1
    spec:
      containers:
      - name: service-1
        image: gxspace/service-1
        imagePullPolicy: Never
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
        ports:
          - containerPort: 3000
        env:
          - name: PORT
            value: "3000"

---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: service-1-destination-rule
spec:
  host: service-1
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
    - name: v1
      labels:
        version: v1
      trafficPolicy:
        loadBalancer:
          simple: ROUND_ROBIN

---

apiVersion: v1
kind: Service
metadata:
  name: service-1
spec:
  selector:
    app: service-1
  ports:
  - port: 3000
    name: http

